version: '2'

services:
    web:
        image: teuki/midi2mp3:latest
        ports:
            - "80:80"
        volumes:
            - ./apache.conf:/etc/apache2/sites-available/000-default.conf
            - ./api:/var/www
        environment:
            - DOCUMENT_ROOT=public
            - UID=33
