version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./api:/api
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network
    php:
        image: php:fpm
        volumes:
            - ./api:/api
            - ./php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - api-network

networks:
    api-network:
        driver: bridge
