version: '2'

services:
    front-web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./dist:/public
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
