version: '2'

services:
    cnb2lp-web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./public:/public
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
