version: '2'

services:

    # -------------------------
    # Facade : reverse proxy 
    # -------------------------

    api-facade:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - cnb2lp-web
            - lilypond-web
            - midi2mp3-web
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network
        #restart: always


    # -------------------------
    # Microservice : cnb2lp
    # -------------------------

    cnb2lp-web:
        image: nginx:latest
        expose:
            - "80"
        depends_on:
            - cnb2lp-php
        volumes:
            - ../services/cnb2lp/api:/api
            - ../services/cnb2lp/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network

    cnb2lp-php:
        image: php:fpm
        volumes:
            - ../services/cnb2lp/api:/api
            - ../services/cnb2lp/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - api-network


    # -------------------------
    # Microservice : lilypond
    # -------------------------

    lilypond-web:
        image: teuki/lilypond:latest
        expose:
            - "80"
        volumes:
            - ../services/lilypond/apache.conf:/etc/apache2/sites-available/000-default.conf
            - ../services/lilypond/api:/var/www
            - ../services/lilypond/data:/data
        environment:
            - DOCUMENT_ROOT=public
        networks:
            - api-network

    # -------------------------
    # Microservice : midi2mp3
    # -------------------------

    midi2mp3-web:
        image: nginx:latest
        expose:
            - "80"
        depends_on:
            - midi2mp3-php
        volumes:
            - ../services/midi2mp3/api:/api
            - ../services/midi2mp3/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network

    midi2mp3-php:
        image: php:fpm
        volumes:
            - ../services/midi2mp3/api:/api
            - ../services/midi2mp3/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - api-network

networks:
    api-network:
        driver: bridge
